---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:7.8.3
  amd64: ghcr.io/hassio-addons/debian-base/amd64:7.8.3
  armv7: ghcr.io/hassio-addons/debian-base/armv7:7.8.3
args:
  WYOMING_ONNX_ASR_VERSION: 0.3.1
